version: "3.9"
services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    environment:
      TZ: Asia/Jakarta
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pwd}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pwd}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-users}
    restart: unless-stopped
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD:-pwd}"]
      interval: 0.5s
      timeout: 10s
      retries: 10
  golang-clean-architecture:
    build:
      context: .
      dockerfile: Dockerfile # Specify the path to your Dockerfile
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ./config/config-local.yaml:/app/config/config-local.yaml
    depends_on:
      - mysql-db
